name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/eduvami/mongodbapi:latest
    - name: push-to-ghcr
      uses: macbre/push-to-ghcr@v8
      with:
        image_name: mongodbapi
        github_token: ${{ secrets.GITHUB_TOKEN }}
    

      
